### ISSUE TITLE
Possible file naming bug in bin/process_vsgs.py

### ISSUE THREAD

**Issue by marija-kra** [goldrieve/vsgseq2#1]
Hello!

While running vsgseq2 I stumbled upon what might be a bug (which was easy to fix). I was running the full vsgseq2 pipeline, but it kept crashing at the BLAST stage (actually, when running process_vsgs.py). The problem was that it couldn't find the "_VSGs.fasta" file. It had created the following file:
IL3000-CL1-P11-1_S29_L001_R1_001_VSGs.fasta

But it was looking for the following file:
IL3000-CL1-P11-1_S29_L001_R1_001.fastq_VSGs.fasta

What fixed the issue is replacing the following line in bin/process_vsgs.py with the one below it:

outfile = open(inputfile.split('.')[0]+'_VSGs.fasta', 'w')

outfile = open(inputfile + '_VSGs.fasta', 'w')

And now it works!

**Comment by goldrieve** [comment]
Discussed with @marija-kra and the issue was likely caused by changes made to the main.nf file before execution. I will update README to clarify Nextflow execution commands and highlight that no changes need to be made to the main.nf file to run vsgseq2 - options should be provided as flags at the command line execution.

**Comment by LSinger-bio** [comment]
Hello! I am having a similar issue, but I haven't changed the main.nf file. I was able to run the tutorial data fine, but when I tried with my own I get the following error:

> ERROR ~ Error executing process > 'BLAST (1)'

> Caused by:
>  Missing output file(s) `Control_A_10_7.fastq_VSGs.fasta` expected by process `BLAST (1)`

It looks like it was looking for a file called "Control_A_10_7.fastq_VSGs.fasta", but the file it had written was "Control_A_10_7_VSGs.fasta".
